# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    # Raise all npm pull requests with assignees
    assignees:
      - "mcarter-astronautdev"
    groups:
      # Group all npm updates into a single pull request
      dependencies:
        patterns:
          - "*"

  # Keep GitHub Actions dependencies up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    # Raise all GitHub Actions pull requests with assignees
    assignees:
      - "mcarter-astronautdev"
    groups:
      # Group all GitHub Actions updates into a single pull request
      actions:
        patterns:
          - "*"
